### ISSUE TITLE
Add a package to the custom modules

### ISSUE THREAD

**Issue by DavidHernandez** [vegantriathlete/md8d-wip#1]
Instead of using the default custom package, I think it might be better to move them to a custom package like md8d or something like that.

https://www.drupal.org/docs/8/creating-custom-modules/let-drupal-8-know-about-your-module-with-an-infoyml-file

**Comment by vegantriathlete** [comment]
Good suggestion. I don't know if it's better to call the package MD8D or IAI; I just went with MD8D.
