### ISSUE TITLE
Follow the code standards

### ISSUE THREAD

**Issue by DavidHernandez** [vegantriathlete/md8d-wip#3]
I've reviewed the coding standards using the Code Sniffers  and I find out several issues that you can see in the attached file.

[review.txt](https://github.com/vegantriathlete/md8d-wip/files/999783/review.txt)

I got the sniffer results using this script here: https://github.com/Gizra/drupal-elm-starter/blob/master/server/run_coder.sh

**Comment by vegantriathlete** [comment]
I'm not worried about the pseudo clients meeting Drupal coding standards.

The Ocean Temperature module is still not complete.

I think that there are false positives on the TourLinkBlock.php (and many other places). At any rate, I'm using special comments for the student comments. I'm ignoring all complaints about the special student comments.

RetrieveEndpoint.php is not going to be used in the final version of the course.

I've looked over everything in the report and have corrected the things that I choose to correct.

4802cfda4d92aae1ffefd1d0167a0398d7ad0fca
